// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type AddCustomerReq struct {
	Email        string `json:"email"`
	CustomerName string `json:"customerName"`
}

type AddCustomerResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type CustomerReq struct {
	CustomerCode string `json:"customerId"`
	CustomerName string `json:"customerName"`
	Page         int32  `json:"page"`
	Size         int32  `json:"size"`
}

type CustomerReply struct {
	CustomerId   int64  `json:"customerId"`
	CustomerName string `json:"customerName"`
	Email        string `json:"email"`
	CreatedDate  string `json:"createdDate"`
}
