// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	AccessToken     string `json:"access_token"`
	AccessExpire    int64  `json:"expires_in"`
	RefreshAfter    int64  `json:"refresh_expires_in"`
	RefreshToken    string `json:"refresh_token"`
	NotBeforePolicy int64  `json:"not-before-policy"`
	TokenType       string `json:"token_type"`
	SessionState    string `json:"session_state"`
	Scope           string `json:"scope"`
}

type AddCommonReq struct {
	Code               string `json:"code"`
	Name               string `json:"name"`
	Description        string `json:"description,optional"`
	OrderNum           int16  `json:"orderNum,optional"`
	Value              string `json:"value,optional"`
	CommonCategoryCode string `json:"commonCategoryCode"`
	IsDefault          bool   `json:"isDefault,default=false"`
}

type AddCommonResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UpdateCommonReq struct {
	Id                 string `json:"id"`
	Code               string `json:"code"`
	Name               string `json:"name"`
	Description        string `json:"description,optional"`
	OrderNum           int32  `json:"orderNum,optional"`
	Value              string `json:"value,optional"`
	CommonCategoryCode string `json:"commonCategoryCode"`
	IsDefault          bool   `json:"isDefault,default=false"`
}

type UpdateCommonResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DeleteCommonReq struct {
	Id string `json:"id"`
}

type DeleteCommonResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type DetailCommonReq struct {
	Id string `json:"id"`
}

type DetailCommonResp struct {
	Id                 string `json:"id"`
	Code               string `json:"code"`
	Name               string `json:"name"`
	Description        string `json:"description,optional"`
	OrderNum           int32  `json:"orderNum,optional"`
	Value              string `json:"value,optional"`
	CommonCategoryCode string `json:"commonCategoryCode"`
	IsDefault          bool   `json:"isDefault,optional"`
}

type ListCommonReq struct {
	Code               string `json:"code,optional"`
	Name               string `json:"name,optional"`
	CommonCategoryCode string `json:"commonCategoryCode,optional"`
	Page               int32  `json:"page,default=0"`
	Size               int32  `json:"size,default=10"`
}

type ListCommonResp struct {
	Id                 string `json:"id"`
	Code               string `json:"code"`
	Name               string `json:"name"`
	Description        string `json:"description,optional"`
	OrderNum           int32  `json:"orderNum,optional"`
	Value              string `json:"value,optional"`
	CommonCategoryCode string `json:"commonCategoryCode"`
	IsDefault          bool   `json:"isDefault,default=false"`
}

type PageCommonResp struct {
	Content      []*ListCommonResp `json:"content"`
	TotalElement int32             `json:"totalElement,default=0"`
	TotalPages   int32             `json:"totalPages,default=0"`
	Size         int32             `json:"size,default=0"`
	Number       int32             `json:"number,default=10"`
}

type DetailCommonCategoryReq struct {
	Id string `json:"id"`
}

type DetailCommonCategoryResp struct {
	Id   string `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type ListCommonCategoryReq struct {
	Code string `json:"code,optional"`
	Name string `json:"name,optional"`
	Page int32  `json:"page,default=0"`
	Size int32  `json:"size,default=10"`
}

type ListCommonCategoryResp struct {
	Id   string `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}
