// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	common "crmcore-customer-go/api/internal/handler/common"
	commoncategory "crmcore-customer-go/api/internal/handler/commoncategory"
	login "crmcore-customer-go/api/internal/handler/login"
	"crmcore-customer-go/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authen},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: common.CommonAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: common.CommonUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: common.CommonDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/detail",
					Handler: common.CommonDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/list",
					Handler: common.CommonListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/common"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authen},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/detail",
					Handler: commoncategory.CommonDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/list",
					Handler: commoncategory.CommonListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/commoncategory"),
	)
}
