// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "apiproduct/api/internal/handler/login"
	product "apiproduct/api/internal/handler/product"
	"apiproduct/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authen},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: product.CustomerAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/list",
					Handler: product.CustomerListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/product"),
	)
}
