// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: category.proto

package categoryclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Category_CommonAdd_FullMethodName    = "/categoryclient.Category/CommonAdd"
	Category_CommonUpdate_FullMethodName = "/categoryclient.Category/CommonUpdate"
	Category_CommonDelete_FullMethodName = "/categoryclient.Category/CommonDelete"
	Category_CommonDetail_FullMethodName = "/categoryclient.Category/CommonDetail"
	Category_CommonList_FullMethodName   = "/categoryclient.Category/CommonList"
)

// CategoryClient is the client API for Category service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryClient interface {
	CommonAdd(ctx context.Context, in *AddCommonReq, opts ...grpc.CallOption) (*AddCommonResp, error)
	CommonUpdate(ctx context.Context, in *UpdateCommonReq, opts ...grpc.CallOption) (*UpdateCommonReq, error)
	CommonDelete(ctx context.Context, in *DeleteCommonReq, opts ...grpc.CallOption) (*DeleteCommonResp, error)
	CommonDetail(ctx context.Context, in *DetailCommonReq, opts ...grpc.CallOption) (*DeleteCommonResp, error)
	CommonList(ctx context.Context, in *ListCommonReq, opts ...grpc.CallOption) (*PageCommonResp, error)
}

type categoryClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryClient(cc grpc.ClientConnInterface) CategoryClient {
	return &categoryClient{cc}
}

func (c *categoryClient) CommonAdd(ctx context.Context, in *AddCommonReq, opts ...grpc.CallOption) (*AddCommonResp, error) {
	out := new(AddCommonResp)
	err := c.cc.Invoke(ctx, Category_CommonAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) CommonUpdate(ctx context.Context, in *UpdateCommonReq, opts ...grpc.CallOption) (*UpdateCommonReq, error) {
	out := new(UpdateCommonReq)
	err := c.cc.Invoke(ctx, Category_CommonUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) CommonDelete(ctx context.Context, in *DeleteCommonReq, opts ...grpc.CallOption) (*DeleteCommonResp, error) {
	out := new(DeleteCommonResp)
	err := c.cc.Invoke(ctx, Category_CommonDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) CommonDetail(ctx context.Context, in *DetailCommonReq, opts ...grpc.CallOption) (*DeleteCommonResp, error) {
	out := new(DeleteCommonResp)
	err := c.cc.Invoke(ctx, Category_CommonDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) CommonList(ctx context.Context, in *ListCommonReq, opts ...grpc.CallOption) (*PageCommonResp, error) {
	out := new(PageCommonResp)
	err := c.cc.Invoke(ctx, Category_CommonList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServer is the server API for Category service.
// All implementations must embed UnimplementedCategoryServer
// for forward compatibility
type CategoryServer interface {
	CommonAdd(context.Context, *AddCommonReq) (*AddCommonResp, error)
	CommonUpdate(context.Context, *UpdateCommonReq) (*UpdateCommonReq, error)
	CommonDelete(context.Context, *DeleteCommonReq) (*DeleteCommonResp, error)
	CommonDetail(context.Context, *DetailCommonReq) (*DeleteCommonResp, error)
	CommonList(context.Context, *ListCommonReq) (*PageCommonResp, error)
	mustEmbedUnimplementedCategoryServer()
}

// UnimplementedCategoryServer must be embedded to have forward compatible implementations.
type UnimplementedCategoryServer struct {
}

func (UnimplementedCategoryServer) CommonAdd(context.Context, *AddCommonReq) (*AddCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommonAdd not implemented")
}
func (UnimplementedCategoryServer) CommonUpdate(context.Context, *UpdateCommonReq) (*UpdateCommonReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommonUpdate not implemented")
}
func (UnimplementedCategoryServer) CommonDelete(context.Context, *DeleteCommonReq) (*DeleteCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommonDelete not implemented")
}
func (UnimplementedCategoryServer) CommonDetail(context.Context, *DetailCommonReq) (*DeleteCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommonDetail not implemented")
}
func (UnimplementedCategoryServer) CommonList(context.Context, *ListCommonReq) (*PageCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommonList not implemented")
}
func (UnimplementedCategoryServer) mustEmbedUnimplementedCategoryServer() {}

// UnsafeCategoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryServer will
// result in compilation errors.
type UnsafeCategoryServer interface {
	mustEmbedUnimplementedCategoryServer()
}

func RegisterCategoryServer(s grpc.ServiceRegistrar, srv CategoryServer) {
	s.RegisterService(&Category_ServiceDesc, srv)
}

func _Category_CommonAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).CommonAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Category_CommonAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).CommonAdd(ctx, req.(*AddCommonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_CommonUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).CommonUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Category_CommonUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).CommonUpdate(ctx, req.(*UpdateCommonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_CommonDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).CommonDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Category_CommonDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).CommonDelete(ctx, req.(*DeleteCommonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_CommonDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailCommonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).CommonDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Category_CommonDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).CommonDetail(ctx, req.(*DetailCommonReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_CommonList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).CommonList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Category_CommonList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).CommonList(ctx, req.(*ListCommonReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Category_ServiceDesc is the grpc.ServiceDesc for Category service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Category_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "categoryclient.Category",
	HandlerType: (*CategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommonAdd",
			Handler:    _Category_CommonAdd_Handler,
		},
		{
			MethodName: "CommonUpdate",
			Handler:    _Category_CommonUpdate_Handler,
		},
		{
			MethodName: "CommonDelete",
			Handler:    _Category_CommonDelete_Handler,
		},
		{
			MethodName: "CommonDetail",
			Handler:    _Category_CommonDetail_Handler,
		},
		{
			MethodName: "CommonList",
			Handler:    _Category_CommonList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "category.proto",
}
